#!/bin/bash
# Stage 2 Test: Print Basic Packet Info (Timestamp and Length)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

pass() { echo -e "${GREEN}PASS${NC}: $1"; }
fail() { echo -e "${RED}FAIL${NC}: $1"; echo "Output was:"; cat /tmp/sniffer_output.txt; exit 1; }
info() { echo -e "${YELLOW}INFO${NC}: $1"; }

echo "========================================="
echo "Stage 2: Print Basic Packet Info"
echo "========================================="
echo

# Check if binary exists
if [ ! -f "./sniffer" ]; then
    fail "Binary not found. Run 'make' first."
fi

# Cleanup from any previous run
rm -f /tmp/sniffer_output.txt

# Start sniffer
info "Starting packet sniffer..."
sudo ./sniffer > /tmp/sniffer_output.txt 2>&1 &
SNIFFER_PID=$!
sleep 2

# Check if process is running
if ! ps -p $SNIFFER_PID > /dev/null 2>&1; then
    fail "Sniffer process died immediately. Check for crashes."
fi

# Test 1: Regression - Still captures packets
info "Test 1: Regression - Program still captures packets"
pass "Program starts and runs"

# Test 2: Generate traffic
info "Test 2: Generating ICMP traffic (ping)"
ping -c 5 127.0.0.1 > /dev/null 2>&1 &
PING_PID=$!
sleep 3

# Stop sniffer
sudo kill $SNIFFER_PID 2>/dev/null || true
wait $SNIFFER_PID 2>/dev/null || true
wait $PING_PID 2>/dev/null || true

# Verify we have output
if [ ! -s /tmp/sniffer_output.txt ]; then
    fail "No output generated by sniffer"
fi

# Test 3: Check for "Packet captured" message
info "Test 3: Output contains 'Packet captured' messages"
if ! grep -q "Packet captured" /tmp/sniffer_output.txt; then
    fail "No 'Packet captured' messages found"
fi
PACKET_COUNT=$(grep -c "Packet captured" /tmp/sniffer_output.txt || echo "0")
if [ "$PACKET_COUNT" -lt 1 ]; then
    fail "Expected at least 1 packet, got $PACKET_COUNT"
fi
pass "Found $PACKET_COUNT packet capture messages"

# Test 4: Timestamp format validation
info "Test 4: Timestamp format [YYYY-MM-DD HH:MM:SS.microseconds]"
# Look for pattern: [YYYY-MM-DD HH:MM:SS.microseconds]
# Example: [2026-01-07 14:23:45.123456]
if ! grep -E '\[[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}\]' /tmp/sniffer_output.txt > /dev/null; then
    fail "Timestamp format incorrect. Expected: [YYYY-MM-DD HH:MM:SS.microseconds]"
fi
pass "Timestamp format is correct"

# Test 5: Timestamp reasonableness (not in past/far future)
info "Test 5: Timestamps are reasonable (current time)"
# Extract a timestamp and validate year is current
CURRENT_YEAR=$(date +%Y)
if ! grep -E "\[$CURRENT_YEAR-" /tmp/sniffer_output.txt > /dev/null; then
    fail "Timestamp year does not match current year ($CURRENT_YEAR)"
fi
pass "Timestamps contain current year"

# Test 6: Captured length (caplen) present
info "Test 6: Output contains captured length (caplen)"
if ! grep -E '[0-9]+ bytes captured' /tmp/sniffer_output.txt > /dev/null; then
    fail "Missing 'X bytes captured' in output"
fi
pass "Captured length (caplen) is present"

# Test 7: Total length (len) present
info "Test 7: Output contains total length (len)"
if ! grep -E '[0-9]+ bytes total' /tmp/sniffer_output.txt > /dev/null; then
    fail "Missing 'X bytes total' in output"
fi
pass "Total length (len) is present"

# Test 8: Byte counts are reasonable
info "Test 8: Byte counts are reasonable (> 0, typical packet sizes)"
# Extract byte values and verify they're in reasonable range (1-65535)
BYTE_VALUES=$(grep -oE '[0-9]+ bytes (captured|total)' /tmp/sniffer_output.txt | grep -oE '^[0-9]+' || echo "")
if [ -z "$BYTE_VALUES" ]; then
    fail "Could not extract byte count values"
fi

# Check each value is reasonable
while IFS= read -r BYTES; do
    if [ "$BYTES" -lt 1 ] || [ "$BYTES" -gt 65535 ]; then
        fail "Byte count $BYTES is outside reasonable range (1-65535)"
    fi
done <<< "$BYTES_VALUES"
pass "Byte counts are in reasonable range"

# Test 9: Complete format validation
info "Test 9: Complete output format validation"
# Check for full format: [timestamp] Packet captured: N bytes captured, M bytes total
if ! grep -E '\[[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{6}\] Packet captured: [0-9]+ bytes captured, [0-9]+ bytes total' /tmp/sniffer_output.txt > /dev/null; then
    fail "Complete output format does not match expected pattern"
fi
pass "Complete output format matches specification"

# Test 10: Microseconds are present and non-zero
info "Test 10: Timestamps include microseconds"
# Extract microsecond portion and verify it exists
MICROSECONDS=$(grep -oE '\.[0-9]{6}\]' /tmp/sniffer_output.txt | head -1 || echo "")
if [ -z "$MICROSECONDS" ]; then
    fail "Microseconds not found in timestamp"
fi
pass "Microseconds are present in timestamps"

# Show sample output for verification
echo
info "Sample output (first 3 packets):"
grep "Packet captured" /tmp/sniffer_output.txt | head -3 || true

# Cleanup
rm -f /tmp/sniffer_output.txt

echo
echo "========================================="
echo -e "${GREEN}Stage 2: All tests passed!${NC}"
echo "========================================="
echo
echo "Next: Run '/validate-stage' to verify completion"
echo "Then: Run '/next-stage' to advance to Stage 3"
